# Part of the new RegimeVAE architecture as of 2025-10-13

from dataclasses import dataclass
from typing import List

from sasaie_core.api.action import ActionType

@dataclass
class Policy:
    """Represents a potential policy/action sequence generated by the planner."""
    action_type: ActionType
    actions: List[float]  # Sequence of actions
    horizon: int
    expected_reward: float = 0.0
    information_gain: float = 0.0
    efe: float = float('inf')  # Expected Free Energy
